export const FETCH_PRODUCTS_LIST = 'FETCH_PRODUCTS_LIST';
export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREASE_CART_ITEM_QUANTITY = 'INCREASE_CART_ITEM_QUANTITY';
export const DECREASE_CART_ITEM_QUANTITY = 'DECREASE_CART_ITEM_QUANTITY';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
